apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: backend
  labels:
    app.kubernetes.io/name: employee-directory
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  # These are placeholder values - actual secrets are retrieved from AWS Secrets Manager via IRSA
  # The application will use the secret names configured in the deployment environment variables
  PLACEHOLDER: "secrets-managed-by-aws-secrets-manager"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-config
  namespace: frontend
  labels:
    app.kubernetes.io/name: employee-directory
    app.kubernetes.io/component: frontend
type: Opaque
stringData:
  REACT_APP_API_URL: "/api"