apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-service-account
  namespace: backend
  labels:
    app.kubernetes.io/name: employee-directory
    app.kubernetes.io/component: backend
  annotations:
    # IRSA annotation - will be updated by deployment script
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/employee-directory-backend-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-service-account
  namespace: frontend
  labels:
    app.kubernetes.io/name: employee-directory
    app.kubernetes.io/component: frontend
  annotations:
    # IRSA annotation for frontend if needed in the future
    # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/employee-directory-frontend-role